# This is the config file for landscape.io
# https://landscape.io/pages/docs
# https://landscape.io/github/astropy/pyregion/

ignore-paths:
    - docs/conf.py
    - pyregion/version.py
    - pyregion/conftest.py
    - pyregion/_astropy_init.py
    - pyregion/cython_version.py
    - ah_bootstrap.py
    - ez_setup.py
