language: python

python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4

env:
    # try all python versions with the latest stable numpy and astropy
    - ASTROPY_VERSION=stable NUMPY_VERSION=1.9.0 SETUP_CMD='test'

matrix:
    include:
        # try latest developer version of astropy
        - python: 2.7
          env: ASTROPY_VERSION=development NUMPY_VERSION=1.7.1 SETUP_CMD='test'
        - python: 3.3
          env: ASTROPY_VERSION=development NUMPY_VERSION=1.9.0 SETUP_CMD='test'
        - python: 3.4
          env: ASTROPY_VERSION=development NUMPY_VERSION=1.9.0 SETUP_CMD='test'

before_install:

    # Use utf8 encoding. Should be default, but this is insurance against
    # future changes
    - export PYTHONIOENCODING=UTF8

    # Install conda
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

    # We do this to make sure we get the dependencies so pip works below
    - sudo apt-get install graphviz texlive-latex-extra dvipng

install:

    # CONDA
    - conda create --yes -n test -c astropy-ci-extras python=$TRAVIS_PYTHON_VERSION
    - source activate test

    # CORE DEPENDENCIES
    - conda install --yes -c astropy-ci-extras numpy=$NUMPY_VERSION pytest pip Cython matplotlib sphinx pyparsing

    - if [[ $ASTROPY_VERSION == stable ]]; then conda install --yes -c astropy-ci-extras astropy; fi
    - if [[ $ASTROPY_VERSION == development ]]; then pip install git+http://github.com/astropy/astropy.git#egg=astropy --use-mirrors; fi

script:
   - python setup.py build_ext --inplace
   - py.test pyregion
   - cd docs
   - python make.py
